language: php

php:
  - 5.4
  - 5.5

before_install:
  - composer self-update

before_script:
  - sudo apt-get install graphviz
  - composer update --dev
  - pyrus install -f pear/PHP_CodeSniffer-1.5.2
  - git clone https://github.com/joomla/coding-standards.git `pyrus get php_dir | tail -1`/PHP/CodeSniffer/Standards/Joomla
  - phpenv rehash

script:
  - ant composervalidate
  - ant phpcs
  - ant phpunit

after_script:
  - utility/initiate-publish.sh

after_success:
  - ant phpdoc

env:
  global:
    - secure: "RT1zLx1CASx0obYvrmwwMc4Ro3aJx5FjB/X4pH04YQQDMjXgLG+Yu/yCZHd1v+TUJzRUstxNJdOJyIMu0inKwdLxbUayz0hy6nWGDeYTddu8bDHBa7RRgOJe6io+oFkjq196kjFPkfvvWz8QSqylbey3VJq0Eiv5n/ZG892vTa0="
