language: php

php:
  - 5.4
  - 5.5

before_install:
  - composer self-update

before_script:
  - sudo apt-get install graphviz
  - composer update --dev
  - pyrus install -f pear/PHP_CodeSniffer-1.5.2
  - git clone https://github.com/joomla/coding-standards.git `pyrus get php_dir | tail -1`/PHP/CodeSniffer/Standards/Joomla
  - phpenv rehash

script:
  - ant composervalidate
  - ant phpcs
  - ant phpunit

after_script:
  - utility/initiate-publish.sh

after_success:
  - ant phpdoc

env:
  global:
    - secure: "aeja0orxbbFxLG8PFZANIKGLBg0zOH1UvXv0/61SWWlliqp7S8kJOH15bPvFj3K646DUq0rqRBCAJ3MxYjFH9qmQeeIDWlN7qvpyYJbFZqHsr5oG0F1uEa2xeCFh6spaHRmA6p0DoZehye6crS7eaQMIue41w9Qx9eyZB+piROk="
